version: '3'

volumes:
  registry_data:

services:
  bootstrap-registry:
    env_file:
      - .env
    restart: "no"
    image: registry:2.7.0
    entrypoint: /bin/sh
    command: /bootstrap.sh
    volumes:
      - ./bootstrap.sh:/bootstrap.sh:ro
      - ./auth:/auth
    environment:
      BASIC_AUTH_USERNAME: "${BASIC_AUTH_USERNAME:-docker}"
      BASIC_AUTH_PASSWORD: "${BASIC_AUTH_PASSWORD:-changeme123}"
      REGISTRY_AUTH_HTPASSWD_PATH: "${REGISTRY_AUTH_HTPASSWD_PATH}"

  registry:
    env_file:
      - .env
    restart: "always"
    image: registry:2.7.0
    ports:
      - 4443:443
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:443"
      REGISTRY_HTTP_TLS_CERTIFICATE: "${REGISTRY_HTTP_TLS_CERTIFICATE:-/certs/dockyard-example.crt}"
      REGISTRY_HTTP_TLS_KEY: "${REGISTRY_HTTP_TLS_KEY:-/certs/dockyard-example.key}"
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_PATH: "${REGISTRY_AUTH_HTPASSWD_PATH}"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
    volumes:
      - registry_data:/var/lib/registry
      - ./certs:/certs:ro
      - ./auth:/auth:ro
    depends_on:
      - bootstrap-registry

